#!/usr/bin/python3
#import time
#start = time.time()
import sys

def getFactor(n):
    if n == 1:
        return [1, 1]
    if n == 2:
        return [1, 2]
    for i in range(2, n):
        if not (n % i):
            return [i, int(n / i)]
    return [1, n]

f = open(sys.argv[1],"r")

for l in f:
    n = int(l)
    fa = getFactor(n)
    print(f"{n}={fa[1]}*{fa[0]}")
f.close()
#end = time.time()
#print(f"time ={end - start}")