#!/usr/bin/python3
from math import *




def prime_sqrt(n):
    for i in range(2,round(sqrt(n))+1):
        if n % i == 0:
            return i
    return 1

print(prime_sqrt(1718944270642558716715))